
################# pretrained model ###########################
hifi_model_path: "hifivoice/pretrained/UNIVERSAL_V1/g_02500000"
hifi_config_path: "hifivoice/pretrained/UNIVERSAL_V1/config.json"

wav2mel_model_path: "Any2Any/model/dvector/pre_model/wav2mel.pt"
dvector_model_path: "Any2Any/model/dvector/pre_model/dvector-step250000.pt"

pre_train_singlevc: True
singlevc_model_path: "Any2Any/model/checkpoint-3000.pt"



################# infer config ###########################
test_wav_dir: "VCTK-Corpus/wav22050/"
out_dir: "Any2Any/output/"

batch_size: 1
resume_path: "Any2Any/model/checkpoint-3900.pt"

num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
sampling_rate: 22050
fmin: 0
fmax: 8000
num_workers: 1