
################# pretrained model ###########################

wav2mel_model_path: "Any2Any/model/dvector/pre_model/wav2mel.pt"
dvector_model_path: "Any2Any/model/dvector/pre_model/dvector-step250000.pt"


################# config ###########################
wav_dir: "VCTK-Corpus/wav22050/"
out_dir: "Any2Any/pre_feature"

num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
sampling_rate: 22050
fmin: 0
fmax: 8000
